default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: pass
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_dev

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: Recipe_App_production
  username: recipe-app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
